DELETE FROM perfil_permissoes WHERE perfil_id = 1;
INSERT INTO perfil_permissoes (perfil_id, permissao) VALUES
(1, 'VIEW_DASHBOARD'),
(1, 'MANAGE_USERS'),
(1, 'MANAGE_ROLES'),
(1, 'VIEW_COTAS'),
(1, 'MANAGE_COTAS'),
(1, 'VIEW_GRUPOS'),
(1, 'MANAGE_GRUPOS'),
(1, 'VIEW_FINANCEIRO'),
(1, 'MANAGE_FINANCEIRO'),
(1, 'VIEW_COMPLIANCE'),
(1, 'MANAGE_COMPLIANCE'),
(1, 'VIEW_MEUS_DADOS'),
(1, 'VIEW_CLIENTES'),
(1, 'MANAGE_CLIENTES'),
(1, 'VIEW_RELATORIOS'),
(1, 'MANAGE_VENDAS');
