spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
logging.level.org.hibernate.SQL=INFO

# Em demo rodamos localmente sem https
api.security.cookie.secure=false
api.security.token.secret=8A2D3C4B5E6F7G8H9I0J1K2L3M4N5O6P7Q8R9S0T1U2V3W4X5Y6Z7A8B9C0D1E2F

# Actuator para mostrar profissionalismo
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
