# Nome da aplicação
spring.application.name=consorcio-api

# Configurações de Conexão com o PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/consorcio_db
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate / JPA
# O 'update' cria ou atualiza as tabelas automaticamente com base nas nossas classes Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect