package br.com.estudo.consorcio.domain.model;

public enum StatusCota {
    DISPONIVEL,
    AGUARDANDO_PAGAMENTO,
    ATIVA,
    CANCELADA,
    CONTEMPLADA,
    AGUARDANDO_ANALISE,
    APROVADO,
    INADIMPLENTE,
    SUSPENSA,
    JURIDICO,
    EXCLUIDA,
    QUITADA,
    PENDENTE_INTEGRALIZACAO,
    NAO_COMERCIALIZADA,
    AGUARDANDO_INAUGURACAO,
    EM_EXECUCAO
}