ALTER TABLE grupos ADD COLUMN IF NOT EXISTS versao BIGINT NOT NULL DEFAULT 0;
ALTER TABLE cotas ADD COLUMN IF NOT EXISTS versao BIGINT NOT NULL DEFAULT 0;
ALTER TABLE parcelas ADD COLUMN IF NOT EXISTS versao BIGINT NOT NULL DEFAULT 0;
ALTER TABLE assembleias ADD COLUMN IF NOT EXISTS versao BIGINT NOT NULL DEFAULT 0;
