INSERT INTO contas_contabeis (codigo_cosif, nome, tipo, natureza) VALUES
-- ATIVOS
('1.1.0.00', 'CAIXA E EQUIVALENTES (DISPONIBILIDADES)', 'ATIVO', 'DEVEDORA'),
('1.2.0.00', 'DIREITOS A RECEBER - PROVISÃO DE JUROS E MULTAS', 'ATIVO', 'DEVEDORA'),

-- PASSIVOS (OBRIGAÇÕES COM O GRUPO / ADMINISTRADORA)
('2.1.0.01', 'FUNDO COMUM ARRECADADO', 'PASSIVO', 'CREDORA'),
('2.1.0.02', 'FUNDO DE RESERVA ARRECADADO', 'PASSIVO', 'CREDORA'),
('2.1.0.03', 'TAXA DE ADMINISTRAÇÃO A REPASSAR', 'PASSIVO', 'CREDORA'),
('2.1.0.04', 'SEGURO PRESTAMISTA A REPASSAR', 'PASSIVO', 'CREDORA'),

-- RECEITAS
('3.1.0.01', 'RENDIMENTO DE APLICAÇÃO - FUNDO COMUM', 'RECEITA', 'CREDORA');
